name: "Environment Information"
description: "Retrieve environment information like secret names, account IDs, etc."

inputs:
  environment:
    description: "Environment name (master, prod, dev, security, etc...)"
    required: true

outputs:
  aws-account-id-key:
    value: ${{ steps.aws-keys.outputs.aws-account-id-key }}
    description: "AWS Account ID Key"
  aws-region-key:
    value: ${{ steps.aws-keys.outputs.aws-region-key }}
    description: "AWS Region Key"

runs:
  using: "composite"
  steps:
    - name: Uppercase environment name
      id: uppercase-env
      shell: bash
      run: |
        echo "ENVIRONMENT_UPPERCASE=$(echo ${{ inputs.environment }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

    - name: Define AWS account ID and region keys
      id: aws-keys
      shell: bash
      run: |
        echo "aws-account-id-key=${{ format('{0}_AWS_ACCOUNT_ID', env.ENVIRONMENT_UPPERCASE) }}" >> $GITHUB_OUTPUT
        echo "aws-region-key=${{ format('{0}_AWS_ACCOUNT_REGION', env.ENVIRONMENT_UPPERCASE) }}" >> $GITHUB_OUTPUT
