name: "Unlock state"
on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Lock ID to be unlocked"
        required: true
      environment:
        description: "Environment to apply changes to"
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read
  pull-requests: write
  id-token: write


concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  unlock:
    name: Unlock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Uppercase environment name
        run: echo "ENVIRONMENT_UPPERCASE=$(echo ${{ env.ENVIRONMENT }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCOUNT_ID: ${{ vars[format('{0}_AWS_ACCOUNT_ID', env.ENVIRONMENT_UPPERCASE )] }}
          AWS_ACCOUNT_REGION: ${{ vars[format('{0}_AWS_ACCOUNT_REGION', env.ENVIRONMENT_UPPERCASE )] }}
        with:
          aws-region: ${{ env.AWS_ACCOUNT_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github

      - name: Terraform Unlock
        uses: dflook/terraform-unlock-state@v1
        with:
          lock_id: ${{ github.event.inputs.lock_id }}
          var_file: |
            vars/${{ env.ENVIRONMENT }}.tfvars
          backend_config_file: backends/${{ env.ENVIRONMENT }}.s3.tfbackend
          auto_approve: true